const todos = [
    {
      id: 1,
      name: "demo task",
      clientName: "Client A",
      userId: 1,
      type: "todo",
      fileCount: 0,
      files: [],
    },
    {
      id: 2,
      name: "in-progress task",
      clientName: "Client B",
      userId: 2,
      type: "doing",
      fileCount: 1,
      files: ["file1.pdf"],
    },
    {
      id: 3,
      name: "completed task",
      clientName: "Client C",
      userId: 3,
      type: "complete",
      fileCount: 2,
      files: ["file2.pdf", "file3.pdf"],
    },
    {
      id: 4,
      name: "task to be reviewed",
      clientName: "Client D",
      userId: 4,
      type: "under-review",
      fileCount: 1,
      files: ["file4.pdf"],
    },
    {
      id: 5,
      name: "incomplete task",
      clientName: "Client E",
      userId: 5,
      type: "incomplete",
      fileCount: 0,
      files: [],
    },
    {
      id: 6,
      name: "another todo task",
      clientName: "Client F",
      userId: 6,
      type: "todo",
      fileCount: 3,
      files: ["file5.pdf", "file6.pdf", "file7.pdf"],
    },
    {
      id: 7,
      name: "another in-progress task",
      clientName: "Client G",
      userId: 7,
      type: "doing",
      fileCount: 2,
      files: ["file8.pdf", "file9.pdf"],
    },
    {
      id: 8,
      name: "recently completed task",
      clientName: "Client H",
      userId: 8,
      type: "complete",
      fileCount: 4,
      files: ["file10.pdf", "file11.pdf", "file12.pdf", "file13.pdf"],
    },
    {
      id: 9,
      name: "task waiting for review",
      clientName: "Client I",
      userId: 9,
      type: "under-review",
      fileCount: 1,
      files: ["file14.pdf"],
    },
    {
      id: 10,
      name: "another incomplete task",
      clientName: "Client J",
      userId: 10,
      type: "incomplete",
      fileCount: 0,
      files: [],
    },
    {
      id: 11,
      name: "urgent task",
      clientName: "Client K",
      userId: 11,
      type: "todo",
      fileCount: 0,
      files: [],
    },
    {
      id: 12,
      name: "maintenance task",
      clientName: "Client L",
      userId: 12,
      type: "doing",
      fileCount: 2,
      files: ["file15.pdf", "file16.pdf"],
    },
    {
      id: 13,
      name: "finalized project",
      clientName: "Client M",
      userId: 13,
      type: "complete",
      fileCount: 3,
      files: ["file17.pdf", "file18.pdf", "file19.pdf"],
    },
    {
      id: 14,
      name: "awaiting review from manager",
      clientName: "Client N",
      userId: 14,
      type: "under-review",
      fileCount: 1,
      files: ["file20.pdf"],
    },
    {
      id: 15,
      name: "overdue task",
      clientName: "Client O",
      userId: 15,
      type: "incomplete",
      fileCount: 0,
      files: [],
    },
    {
      id: 16,
      name: "new assignment",
      clientName: "Client P",
      userId: 16,
      type: "todo",
      fileCount: 1,
      files: ["file21.pdf"],
    },
    {
      id: 17,
      name: "quality check task",
      clientName: "Client Q",
      userId: 17,
      type: "doing",
      fileCount: 2,
      files: ["file22.pdf", "file23.pdf"],
    },
    {
      id: 18,
      name: "completed documentation",
      clientName: "Client R",
      userId: 18,
      type: "complete",
      fileCount: 5,
      files: [
        "file24.pdf",
        "file25.pdf",
        "file26.pdf",
        "file27.pdf",
        "file28.pdf",
      ],
    },
    {
      id: 19,
      name: "pending approval",
      clientName: "Client S",
      userId: 19,
      type: "under-review",
      fileCount: 1,
      files: ["file29.pdf"],
    },
    {
      id: 20,
      name: "abandoned project",
      clientName: "Client T",
      userId: 20,
      type: "incomplete",
      fileCount: 0,
      files: [],
    },
  
    // Adding 20 more users
    {
      id: 21,
      name: "client request task",
      clientName: "Client U",
      userId: 21,
      type: "todo",
      fileCount: 1,
      files: ["file30.pdf"],
    },
    {
      id: 22,
      name: "task with follow-up",
      clientName: "Client V",
      userId: 22,
      type: "doing",
      fileCount: 3,
      files: ["file31.pdf", "file32.pdf", "file33.pdf"],
    },
    {
      id: 23,
      name: "completed design",
      clientName: "Client W",
      userId: 23,
      type: "complete",
      fileCount: 4,
      files: ["file34.pdf", "file35.pdf", "file36.pdf", "file37.pdf"],
    },
    {
      id: 24,
      name: "client feedback task",
      clientName: "Client X",
      userId: 24,
      type: "under-review",
      fileCount: 2,
      files: ["file38.pdf", "file39.pdf"],
    },
    {
      id: 25,
      name: "pending decision",
      clientName: "Client Y",
      userId: 25,
      type: "incomplete",
      fileCount: 0,
      files: [],
    },
    {
      id: 26,
      name: "new strategy planning",
      clientName: "Client Z",
      userId: 26,
      type: "todo",
      fileCount: 0,
      files: [],
    },
    {
      id: 27,
      name: "testing and validation",
      clientName: "Client AA",
      userId: 27,
      type: "doing",
      fileCount: 3,
      files: ["file40.pdf", "file41.pdf", "file42.pdf"],
    },
    {
      id: 28,
      name: "completed task review",
      clientName: "Client AB",
      userId: 28,
      type: "complete",
      fileCount: 2,
      files: ["file43.pdf", "file44.pdf"],
    },
    {
      id: 29,
      name: "status update task",
      clientName: "Client AC",
      userId: 29,
      type: "under-review",
      fileCount: 1,
      files: ["file45.pdf"],
    },
    {
      id: 30,
      name: "pre-production task",
      clientName: "Client AD",
      userId: 30,
      type: "incomplete",
      fileCount: 0,
      files: [],
    },
    {
      id: 31,
      name: "budget approval task",
      clientName: "Client AE",
      userId: 31,
      type: "todo",
      fileCount: 1,
      files: ["file46.pdf"],
    },
    {
      id: 32,
      name: "product review",
      clientName: "Client AF",
      userId: 32,
      type: "doing",
      fileCount: 2,
      files: ["file47.pdf", "file48.pdf"],
    },
    {
      id: 33,
      name: "client presentation",
      clientName: "Client AG",
      userId: 33,
      type: "complete",
      fileCount: 5,
      files: [
        "file49.pdf",
        "file50.pdf",
        "file51.pdf",
        "file52.pdf",
        "file53.pdf",
      ],
    },
    {
      id: 34,
      name: "preliminary designs",
      clientName: "Client AH",
      userId: 34,
      type: "under-review",
      fileCount: 2,
      files: ["file54.pdf", "file55.pdf"],
    },
    {
      id: 35,
      name: "backlog task",
      clientName: "Client AI",
      userId: 35,
      type: "incomplete",
      fileCount: 0,
      files: [],
    },
    {
      id: 36,
      name: "task feedback",
      clientName: "Client AJ",
      userId: 36,
      type: "todo",
      fileCount: 3,
      files: ["file56.pdf", "file57.pdf", "file58.pdf"],
    },
    {
      id: 37,
      name: "deadline approaching task",
      clientName: "Client AK",
      userId: 37,
      type: "doing",
      fileCount: 1,
      files: ["file59.pdf"],
    },
    {
      id: 38,
      name: "final draft",
      clientName: "Client AL",
      userId: 38,
      type: "complete",
      fileCount: 2,
      files: ["file60.pdf", "file61.pdf"],
    },
    {
      id: 39,
      name: "manager review",
      clientName: "Client AM",
      userId: 39,
      type: "under-review",
      fileCount: 4,
      files: ["file62.pdf", "file63.pdf", "file64.pdf", "file65.pdf"],
    },
    {
      id: 40,
      name: "Another Client",
      clientName: "Client AL",
      userId: 38,
      type: "complete",
      fileCount: 2,
      files: ["file60.pdf", "file61.pdf"],
    },
  ];
  
  module.exports = todos;
  